name: Python Demo API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        run: python main.py

      - name: Subir artefacto (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: pagina-html
          path: index.html
